#35172 Attempt to resolve UnauthorizedAccessException for Mutex
postsharp/Metalama.Backstage pull request #156
Opened 2024-07-12 13:51 UTC by svick

2024-07-12 15:43 UTC, prochan2 approved these changes

2024-07-12 15:44 UTC, prochan2 requested changes
There's a copy of this code in DesignTimeEntryPointManager, that needs to be kept in sync.

2024-07-15 15:10 UTC, svick commented
@prochan2 Thanks, I missed that. Though the `DesignTimeEntryPointManager` project currently only targets .Net Standard and .Net 6, so I had to change that.

2024-07-16 07:15 UTC, prochan2 approved these changes

2024-07-16 07:15 UTC, prochan2 commented on Metalama.Backstage/Utilities/MutexHelper.cs
> +                    logger?.Trace?.Log( "  Creating new mutex." );
```suggestion
```

2024-07-16 07:15 UTC, prochan2 commented on Metalama.Backstage/Utilities/MutexHelper.cs
> +                    var mutexSecurity = new MutexSecurity();
```suggestion
                    logger?.Trace?.Log( "  Creating new mutex with access rule." );
                    var mutexSecurity = new MutexSecurity();
```

2024-07-16 07:15 UTC, prochan2 commented on Metalama.Backstage/Utilities/MutexHelper.cs
>                      return new Mutex( false, mutexName );
```suggestion
                    logger?.Trace?.Log( "  Creating new mutex." );
                    return new Mutex( false, mutexName );
```

2024-07-16 10:14 UTC, merged