#35194 Fix Mute and Snooze buttons for exception notifications
postsharp/Metalama.Backstage pull request #157
Opened 2024-07-15 15:56 UTC by svick

2024-07-16 07:00 UTC, prochan2 requested changes

2024-07-16 09:34 UTC, svick commented on Metalama.Backstage/Infrastructure/CurrentDateTimeProvider.cs
> +        public DateTime Now => DateTime.UtcNow;
I looked at the code and I think we should use UTC everywhere in Backstage, except maybe in tests. So I don't think there is a reason to have two different properties here.

I did find a few places where time handling could be improved, so I did that.

2024-07-16 09:56 UTC, gfraiteur commented on Metalama.Backstage/Infrastructure/CurrentDateTimeProvider.cs
> +        public DateTime Now => DateTime.UtcNow;
Then it would be better to rename the property to `UtcNow` everywhere.

2024-07-16 10:08 UTC, gfraiteur approved these changes
Ok but pls rename the property.

2024-07-17 08:38 UTC, prochan2 approved these changes

2024-07-17 08:38 UTC, merged